services:
  api_service:
    build: ./api_service
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./api_service:/app/api_service
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

  repo_processor_worker:
    build: ./repo_processor_service
    volumes:
      - ./repo_processor_service:/app/repo_processor_service
      - /tmp/gitinsight_clones:/tmp/gitinsight_clones
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

  ai_analyzer_worker:
    build: ./ai_analyzer_service
    volumes:
      - ./ai_analyzer_service:/app/ai_analyzer_service
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app