FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Install git and other system dependencies
RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Make start.sh executable
RUN chmod +x ./start.sh

EXPOSE 8000

# CMD ["uvicorn", "api_service.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["./start.sh"]