FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# No git needed for this service if it only receives text
# RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["python", "-m", "rq", "worker", "-u", "$REDIS_URL", "gitinsight_ai_analysis"]
CMD ["python", "ai_analyzer_service/main.py"]